// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz7OyeqSsOTO39xUbNGNkHOEsxYrXmGBw',
    appId: '1:1081049588204:web:e22c9cc887555c362660c9',
    messagingSenderId: '1081049588204',
    projectId: 'sugar-smart-assist',
    authDomain: 'sugar-smart-assist.firebaseapp.com',
    storageBucket: 'sugar-smart-assist.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_BS7A24xIX-ULJIOgegmzPPtpGckJFVs',
    appId: '1:1081049588204:android:af67b95344f247652660c9',
    messagingSenderId: '1081049588204',
    projectId: 'sugar-smart-assist',
    storageBucket: 'sugar-smart-assist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMZRY4Ig016X3a00wThjEVwUl0mFcXfSc',
    appId: '1:1081049588204:ios:3aeeb035cc4281322660c9',
    messagingSenderId: '1081049588204',
    projectId: 'sugar-smart-assist',
    storageBucket: 'sugar-smart-assist.appspot.com',
    iosBundleId: 'com.example.sugarSmartAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMZRY4Ig016X3a00wThjEVwUl0mFcXfSc',
    appId: '1:1081049588204:ios:4cf0c5e597dcffee2660c9',
    messagingSenderId: '1081049588204',
    projectId: 'sugar-smart-assist',
    storageBucket: 'sugar-smart-assist.appspot.com',
    iosBundleId: 'com.example.sugarSmartAssist.RunnerTests',
  );
}
